apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-active.yaml
  - ingress-preview.yaml
  - secret.yaml

namespace: learning-dev

commonLabels:
  environment: dev

patches:
  - path: rollout-patch.yaml

images:
  - name: mchhikara/spring-app
    newName: mchhikara/spring-app
    newTag: latest