apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rollout-patch.yaml
  - ingress-active.yaml
  - ingress-preview.yaml
  - secret.yaml

namespace: learning

commonLabels:
  environment: dev

images:
  - name: mchhikara/spring-app
    newName: mchhikara/spring-app
    newTag: latest