apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
  labels:
    app: spring-app-svc
  namespace: learning
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 8080