apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app-deployment
spec:
  selector:
    matchLabels:
      app: spring-app
  strategy:
    blueGreen:
      activeService: spring-app-active-svc
      previewService: spring-app-preview-svc
      previewReplicaCount: 1
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - image: mchhikara/spring-app
          imagePullPolicy: Always
          name: spring-app
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cert-vol
              mountPath: config/secret
              readOnly: true
          env:
            - name: env1
              value: value1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: cert-vol
          secret:
            secretName: test-cer
