apiVersion: v1
kind: Service
metadata:
  name: spring-app-active-svc
  labels:
    app: spring-app-active-svc
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 8080